### ISSUE TITLE
Ada Kriteria Khusus?

### ISSUE THREAD

**Issue by taufik-nurrohman** [opensourceindonesia/daftar-proyek-OSS#3]
Maaf sebelumnya, apakah ada kriteria tertentu? Saya punya proyek hobi berbentuk [sistem manajemen konten berbasis PHP](https://github.com/mecha-cms) sejak tahun 2014 yang lalu. Kalau ini bisa masuk kriteria mau Says coba _pull_ 😊

**Comment by ariya** [comment]
Kriterianya ya harus OSS. Silakan buat PR.
